apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  guestbook-name: "MyPopRock Festival 2.0"
  # make sure to "kubectl port-forward service/backend 8081:80"
  backend-uri: "http://backend.minikube.local:8081/guestbook"
